# Primeiro passo é realizar a importacao das bibliotecas

In [1]:
import cv2 as cv
from matplotlib import pyplot as plt
import numpy as np

In [2]:
kernel = np.ones((3, 3), np.uint8) 

# A função redimencionar serve para alterar o tamanho  da imagem que sera apresentada na tela de login

In [3]:
def redimensionar_img(img_name):
    try:
        # faz a leitura da imagem
#         img = cv.imread(img_name, 0)
        img = img_name
        # pega o numero de pixels horizonta e vertical
        h, w = img.shape[:2]

        res = cv.resize(img, (int(w / 2), int(h / 2)), interpolation= cv.INTER_CUBIC )
#         cv.imshow('diminuida', res)
    except IOError:
        print('Erro na leitura do arquivo!')
    return res

# A função de deteccao de bordas:
* O kernel utilizado para a detecção é o filtro laplaciano e sua mascara de matriz (5x5).
* A tonalidade da imagem é transformada utilizando um filtro para deixá-la acinzentada. 

In [4]:
def deteccao_de_bordas(img_name):
    img = img_name
    edges = cv.Canny(img,100,200)
#     cv.imshow('original', img)
#     cv.imshow('bordas', edges)
    
    return edges

# A função Threshold binario
* faz a binarização de uma imagem ou seja, tranformando ela em preto e branco.
* Sendo o metodo adaptivo de gaussian.

In [5]:
def threshold_binario(img_name):
    # Recebendo objeto imagem aberto
    img_o = img_name
    img = cv.cvtColor(img_o, 0)  
    res, img_b = cv.threshold(img,127,255,cv.THRESH_BINARY_INV)

#     cv.imshow('Binarizacao Adaptive Gaussian', img_b) 
    
    return img_b

# Filtros morfologicos

In [6]:
def dilatacao(img_name):
    img = img_name
    img_dilation = cv.dilate(img, kernel, iterations=1) 
#     cv.imshow('Dilatada', img_dilation)
    return img_dilation

In [7]:
def erosao(img_name):
    img = img_name
    img_erosao = cv.erode(img, kernel, iterations=1)
#     cv.imshow('Erosao', img_erosao)
    return img_erosao

In [8]:
def abertura(img_name):
    img = img_name
    abertura = cv.morphologyEx(img, cv.MORPH_OPEN, kernel)
#     cv.imshow('Abertura', abertura)
    return abertura
    

In [9]:
def fechamento(img_name):
    img = img_name
    fechamento = cv.morphologyEx(img, cv.MORPH_CLOSE, kernel)
#     cv.imshow('Fechamento', fechamento)
    return fechamento

# Função skeletonized 

In [10]:
def skeleton(img_name):
    # Read the image as a grayscale image
    img = img_name
    
    # Threshold the image
    img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    ret,img = cv.threshold(img, 127, 255, 0)
    
    
    # Step 1: Create an empty skeleton
    size = np.size(img)
    skel = np.zeros(img.shape, np.uint8)

    # Get a Cross Shaped Kernel
    krl = cv.getStructuringElement(cv.MORPH_CROSS, (3,3))

    # Repeat steps 2-4
    while True:
        #Step 2: Open the image
        open = cv.morphologyEx(img, cv.MORPH_OPEN, krl)
        #Step 3: Substract open from the original image
        temp = cv.subtract(img, open)
        #Step 4: Erode the original image and refine the skeleton
        eroded = cv.erode(img, krl)
        skel = cv.bitwise_or(skel,temp)
        img = eroded.copy()
        # Step 5: If there are no white pixels left ie.. the image has been completely eroded, quit the loop
        if cv.countNonZero(img)==0:
            break

#     cv.imshow('Skeletonized', skel)
    return skel

# A seguir sera chamada a função main

In [12]:
if __name__ == '__main__':
#     Seleciona um arquivo de imagem
    img = 'assets\input\\'+'digital_real3.jpg'
    
    original = cv.imread(img, 0)
    original = redimensionar_img(original)
#     cv.imshow('original', original)

#     ed = deteccao_de_bordas(original)  
    tr = threshold_binario(original)   
# #     fe = fechamento(ed) 
    di = dilatacao(tr)
    er = erosao(di)
    op = abertura(er)
#     er = erosao(di)
    
    sklt = skeleton(op)
    
#     Essa ultima parte corrige algumas quebras nas minuncias, linhas na horizontal
    kern = np.ones((1,5), np.uint8)  # note this is a horizontal kernel
    d_im = cv.dilate(sklt, kern, iterations=1)
    e_im = cv.erode(d_im, kern, iterations=1) 
    cv.imshow('Fim', e_im)
    
    data_minuncias = [
                        e_im[e_im.shape[0]//3:e_im.shape[0]//4, e_im.shape[0]//3:e_im.shape[1]//4],
                        e_im[e_im.shape[0]//2:e_im.shape[0]//3, e_im.shape[0]//2:e_im.shape[1]//3],
                        e_im[e_im.shape[0]//3:e_im.shape[0]//2, e_im.shape[0]//3:e_im.shape[1]//2],
                        e_im[e_im.shape[0]//4:e_im.shape[0]//5, e_im.shape[0]//4:e_im.shape[1]//5]
                    ]
    print(data_minuncias[0])
    print(data_minuncias[1])
    print(data_minuncias[2])
    print(data_minuncias[3])
    
    cv.waitKey(0)
    cv.destroyAllWindows()
    

    

[]
[]
[[  0   0   0   0   0]
 [  0   0   0   0   0]
 [255 255 255 255   0]
 [  0 255 255   0   0]
 [  0 255 255   0   0]
 [255 255 255 255 255]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0 255 255]
 [  0   0   0   0 255]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [255   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [255 255 255 255   0]
 [  0   0   0   0 255]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0 255]
 [255 255 255 255   0]
 [255 255 255 255   0]
 [  0 255 255 255   0]
 [  0   0   0 255 255]
 [  0   0   0   0 255]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0 255   0   0]
 [  0   0   0   0   0]
 [255 255 255 255 255]
 [255 255 255 255 255]
 [255 255   0   0   0]
 [  0