# Primeiro passo é realizar a importacao das bibliotecas

In [1]:
import cv2 as cv
from matplotlib import pyplot as plt
import numpy as np
from PyQt5 import uic, QtWidgets
import webbrowser, os

In [2]:
kernel = np.ones((3, 3), np.uint8) 

# A função redimencionar serve para alterar o tamanho  da imagem que sera apresentada na tela de login

In [3]:
def redimensionar_img(img_name):
    try:
        # faz a leitura da imagem
#         img = cv.imread(img_name, 0)
        img = img_name
        # pega o numero de pixels horizonta e vertical
        h, w = img.shape[:2]

        res = cv.resize(img, (int(w / 2), int(h / 2)), interpolation= cv.INTER_CUBIC )
#         cv.imshow('diminuida', res)
    except IOError:
        print('Erro na leitura do arquivo!')
    return res

# A função de deteccao de bordas:
* O kernel utilizado para a detecção é o filtro laplaciano e sua mascara de matriz (5x5).
* A tonalidade da imagem é transformada utilizando um filtro para deixá-la acinzentada. 

In [4]:
def deteccao_de_bordas(img_name):
    img = img_name
    edges = cv.Canny(img,100,200)
#     cv.imshow('original', img)
#     cv.imshow('bordas', edges)
    
    return edges

# A função Threshold binario
* faz a binarização de uma imagem ou seja, tranformando ela em preto e branco.
* Sendo o metodo adaptivo de gaussian.

In [5]:
def threshold_binario(img_name):
    # Recebendo objeto imagem aberto
    img_o = img_name
    img = cv.cvtColor(img_o, 0)  
    res, img_b = cv.threshold(img,127,255,cv.THRESH_BINARY_INV)

#     cv.imshow('Binarizacao Adaptive Gaussian', img_b) 
    
    return img_b

# Filtros morfologicos

In [6]:
def dilatacao(img_name):
    img = img_name
    img_dilation = cv.dilate(img, kernel, iterations=1) 
#     cv.imshow('Dilatada', img_dilation)
    return img_dilation

In [7]:
def erosao(img_name):
    img = img_name
    img_erosao = cv.erode(img, kernel, iterations=1)
#     cv.imshow('Erosao', img_erosao)
    return img_erosao

In [8]:
def abertura(img_name):
    img = img_name
    abertura = cv.morphologyEx(img, cv.MORPH_OPEN, kernel)
#     cv.imshow('Abertura', abertura)
    return abertura
    

In [9]:
def fechamento(img_name):
    img = img_name
    fechamento = cv.morphologyEx(img, cv.MORPH_CLOSE, kernel)
#     cv.imshow('Fechamento', fechamento)
    return fechamento

# Função skeletonized 

In [10]:
def skeleton(img_name):
    # Read the image as a grayscale image
    img = img_name
    
    # Threshold the image
    img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    ret,img = cv.threshold(img, 127, 255, 0)
    
    
    # Step 1: Create an empty skeleton
    size = np.size(img)
    skel = np.zeros(img.shape, np.uint8)

    # Get a Cross Shaped Kernel
    krl = cv.getStructuringElement(cv.MORPH_CROSS, (3,3))

    # Repeat steps 2-4
    while True:
        #Step 2: Open the image
        open = cv.morphologyEx(img, cv.MORPH_OPEN, krl)
        #Step 3: Substract open from the original image
        temp = cv.subtract(img, open)
        #Step 4: Erode the original image and refine the skeleton
        eroded = cv.erode(img, krl)
        skel = cv.bitwise_or(skel,temp)
        img = eroded.copy()
        # Step 5: If there are no white pixels left ie.. the image has been completely eroded, quit the loop
        if cv.countNonZero(img)==0:
            break

#     cv.imshow('Skeletonized', skel)
    return skel

# Informacoes dos niveis de acessos

In [11]:
def info_n(nivel):
    if nivel == 1:
        n1 = '''
            Informações do nível 1 - Produção agrícola \n\n



            Nome da unidade produtora (produtor agrícola)\n 

            Endereço do produtor agrícola \n

            Produto(s) agrícolas produzidos \n

            Produção anual em quilogramas \n

            Destino da produção (mercado interno ou exportação) \n

            Número de empregados da unidade produtora \n

            Quantidade de máquinas e implementos aquícolas \n

            Nível de automação da unidade produtora \n
             '''
        nv = 'Nivel 1\nProdução\nAgrícola\n'
        return n1, nv
    elif nivel == 2:
        n2 = '''
            Informações do nível 2 - Informações fiscais \n\n



            Incentivos fiscais recebidos \n

            Impostos municipais pagos \n

            Impostos estaduais recolhidos\n 

            Impostos federais pagos \n

            Taxas federais pagas
             '''
        nv = 'Nivel 2\nInformações\nfiscais'
        return n2, nv
    elif nivel == 3:
        n3 = '''
            Informações do nível 3 - agrotóxicos \n\n



            Agrotóxicos empregados nas produções agrícolas \n



            Onde adquirir as informações: site do Ministério da agricultura,\n
            site do mistério do meio ambiente.\n
             '''
        nv = 'Nivel 3\nAgrotóxicos'
        return n3, nv 

# PyQt5

In [12]:
def exibir_dados(nvl):
    txt, lvl = info_n(nvl)    
    nivel_um_tela.txtN.setText(txt)
    nivel_um_tela.lbl_nivel.setText(lvl)
    nivel_um_tela.show()
    nivel_um_tela.btn_voltar.close()
    
    

In [13]:
def logi_dados():
    name = str(login_tela.txt_user.text())
    if name.upper() == 'jose'.upper():
        lvl = 3
        exibir_dados(lvl)
    elif name.upper() == 'gisele'.upper():
        lvl = 2
        exibir_dados(lvl) 
    elif name.upper() == 'kaka'.upper():
        lvl = 1
        exibir_dados(lvl) 
    elif name.upper() == 'anderson'.upper():
        lvl = 3
        exibir_dados(lvl) 

In [14]:
def cadastro_dados():
    cadastro_tela.show()

In [15]:
def select_digital():
    path="C:/Users"
    caminho = webbrowser.open(os.path.realpath(path))
    login_tela.lbl_digital.setText(caminho)
    return str(caminho)

# A seguir sera chamada a função main

In [ ]:
if __name__ == '__main__':
#     Seleciona um arquivo de imagem
    img = 'assets\input\\'+'digital_real3.jpg'    
    
    
#     obj do pyqt5
    app = QtWidgets.QApplication([])
    login_tela = uic.loadUi('escopo APS/login.ui')
    nivel_um_tela = uic.loadUi('escopo APS/nivel_um.ui')
    cadastro_tela = uic.loadUi('escopo APS/cadastro.ui')
    login_tela.btn_cadastro.clicked.connect(cadastro_dados)
    login_tela.pushButton.clicked.connect(logi_dados)
    login_tela.btn_digital.clicked.connect(select_digital)

    login_tela.show()



    
    original = cv.imread(img, 0)
    original = redimensionar_img(original)
#     cv.imshow('original', original)

#     ed = deteccao_de_bordas(original)  
    tr = threshold_binario(original)   
# #     fe = fechamento(ed) 
    di = dilatacao(tr)
    er = erosao(di)
    op = abertura(er)
#     er = erosao(di)
    
    sklt = skeleton(op)
    
#     Essa ultima parte corrige algumas quebras nas minuncias, linhas na horizontal
    kern = np.ones((1,5), np.uint8)  # note this is a horizontal kernel
    d_im = cv.dilate(sklt, kern, iterations=1)
    e_im = cv.erode(d_im, kern, iterations=1) 
    cv.imshow('Fim', e_im)
    
    data_minuncias = [
                        e_im[e_im.shape[0]//3:e_im.shape[0]//4, e_im.shape[0]//3:e_im.shape[1]//4],
                        e_im[e_im.shape[0]//2:e_im.shape[0]//3, e_im.shape[0]//2:e_im.shape[1]//3],
                        e_im[e_im.shape[0]//3:e_im.shape[0]//2, e_im.shape[0]//3:e_im.shape[1]//2],
                        e_im[e_im.shape[0]//4:e_im.shape[0]//5, e_im.shape[0]//4:e_im.shape[1]//5]
                    ]
    print(data_minuncias[0])
    print(data_minuncias[1])
    print(data_minuncias[2])
    print(data_minuncias[3])
    
#     encerrar OpenCv
    cv.waitKey(0)
    cv.destroyAllWindows()
#     fexar PyQt
    app.exec()
    

    

[]
[]
[[  0   0   0   0   0]
 [  0   0   0   0   0]
 [255 255 255 255   0]
 [  0 255 255   0   0]
 [  0 255 255   0   0]
 [255 255 255 255 255]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0 255 255]
 [  0   0   0   0 255]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [255   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [255 255 255 255   0]
 [  0   0   0   0 255]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0 255]
 [255 255 255 255   0]
 [255 255 255 255   0]
 [  0 255 255 255   0]
 [  0   0   0 255 255]
 [  0   0   0   0 255]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0 255   0   0]
 [  0   0   0   0   0]
 [255 255 255 255 255]
 [255 255 255 255 255]
 [255 255   0   0   0]
 [  0

AttributeError: 'QMainWindow' object has no attribute 'lbl_digital'

AttributeError: 'QMainWindow' object has no attribute 'lbl_digital'